[tool.poetry]
name = "scrapegraphai"

version = "0.5.0"

description = "A web scraping library based on LangChain which uses LLM and direct graph logic to create scraping pipelines."
authors = [
    "Marco Vinciguerra <mvincig11@gmail.com>",
    "Marco Perini <perinim.98@gmail.com>",
    "Lorenzo Padoan <lorenzo.padoan977@gmail.com>"
]
license = "MIT"
readme = "README.md"
homepage = "https://scrapegraph-ai.readthedocs.io/"
repository = "https://github.com/VinciGit00/Scrapegraph-ai"
documentation = "https://scrapegraph-doc.onrender.com/"
keywords = ["scrapegraph", "scrapegraphai", "langchain", "ai", "artificial intelligence", "gpt", "machine learning", "rag", "nlp", "natural language processing", "openai", "scraping", "web scraping", "web scraping library", "web scraping tool", "webscraping", "graph"]
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.9"
langchain = "0.1.14"
langchain-openai = "0.1.1"
langchain-google-genai = "1.0.1"
html2text = "2020.1.16"
faiss-cpu = "1.8.0"
beautifulsoup4 = "4.12.3"
pandas = "2.0.3"
python-dotenv = "1.0.1"
tiktoken = {version = ">=0.5.2,<0.6.0"}
tqdm = "4.66.1"
graphviz = "0.20.1"
google = "3.0.0"
minify-html = "0.15.0"
free-proxy = "1.1.1"
langchain-groq = "0.1.3"
playwright = "^1.43.0"
langchain-aws = "^0.1.2"

[tool.poetry.dev-dependencies]
pytest = "8.0.0"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
sphinx = "7.1.2"
sphinx-rtd-theme = "2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

